// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdNPxwy1ZgaqJYhwid9BWZiPIGy-IMg_U',
    appId: '1:981798495432:android:cf79f14f3a29561745b1fd',
    messagingSenderId: '981798495432',
    projectId: 'cloudmusic-be4b4',
    storageBucket: 'cloudmusic-be4b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQI8xGUFogll0Rxephl4BZafTyaMy92NQ',
    appId: '1:981798495432:ios:491114df3bced7fd45b1fd',
    messagingSenderId: '981798495432',
    projectId: 'cloudmusic-be4b4',
    storageBucket: 'cloudmusic-be4b4.appspot.com',
    iosClientId: '981798495432-qeo1tpactafb484e5223fvrjihglc8pa.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQI8xGUFogll0Rxephl4BZafTyaMy92NQ',
    appId: '1:981798495432:ios:491114df3bced7fd45b1fd',
    messagingSenderId: '981798495432',
    projectId: 'cloudmusic-be4b4',
    storageBucket: 'cloudmusic-be4b4.appspot.com',
    iosClientId: '981798495432-qeo1tpactafb484e5223fvrjihglc8pa.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudMusic',
  );
}
